version: '3.9'
services:
  python3.8:
    build: ./python/3.8/
    tty: true
  python3.9:
    build: ./python/3.9/
    tty: true
  python3.10:
    build: ./python/3.10/
    tty: true
  python3.11:
    build: ./python/3.11/
    tty: true

